@baseUrl = https://vigilant-guacamole-r999xv6pw7jh5rpr-8080.app.github.dev
@url = {{baseUrl}}/cursos
@token = 

### LOGIN - Execute primeiro para obter o token
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "root"
}

###


POST {{url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Desing",
    "descricao": "moda e arte",
    "cargaHoraria": 3000,
    "status": "ativo",
    "horaCriacao": "2022-01-01T00:00:00"
}

###


GET {{url}}

###


GET {{url}}/1

###


PUT {{url}}/1
Content-Type: application/json

{
    "status": "inativo"
}
###