@url = https://vigilant-guacamole-r999xv6pw7jh5rpr-8080.app.github.dev/registros

POST {{url}}
Content-Type: application/json
{
    "dataRegistro": "2020-04-01",
    "status": "ATIVO",
    "alunoId": 1,
    "cursoId": 1
}

###
GET {{url}}

###
PUT {{url}}/1
Content-Type: application/json
{
    "dataRegistro": "2007-04-20",
    "status": "INATIVO",
    "alunoId": 1,
    "cursoId": 1
}